FROM uberspace/docker-compile

ENV GCC_VERSION='4.9.4'
ENV GCC_PATH="gcc-$GCC_VERSION"
ENV GCC_FILE="$GCC_PATH.tar.bz2"
ENV GCC_URL_PATH="ftp://ftp.gwdg.de/pub/misc/gcc/releases/gcc-$GCC_VERSION"
ENV GCC_URL_FILE="$GCC_URL_PATH/$GCC_FILE"
ENV GCC_URL_SHA="$GCC_URL_PATH/sha512.sum"

RUN yum install -y libmpc-devel mpfr-devel gmp-devel

RUN set -ex; \
	cd /tmp && \
	curl --remote-name "$GCC_URL_FILE" && \
	curl "$GCC_URL_SHA" | grep "$GCC_FILE" | sha512sum --check - && \
	tar -xjf "$GCC_FILE" && \
	rm "$GCC_FILE" && \
	cd "$GCC_PATH" && \
	./configure --enable-languages=c,c++ --disable-multilib && \
	make -j4 >/dev/null && \
	make install >/dev/null && \
	cd - && \
	rm -rf "$GCC_PATH"

ENV CC='/usr/local/bin/gcc'
ENV CXX='/usr/local/bin/g++'
ENV PATH="/usr/local/bin:$PATH"
ENV LD_LIBRARY_PATH="/usr/local/lib64:$LD_LIBRARY_PATH"
